spring:
  application:
    name: amazonapi

  datasource:
    url: jdbc:mysql://localhost:3306/amazonapi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: mipassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
